### PR TITLE
Update example to use disk storage with EF Core

### PR DESCRIPTION
**Pull request by khalidabuhakmeh**
The Todo model has been introduced with a migration for the DB setup. Also, the DB set up has been changed to Sqlite in 'Program.cs'. Usage of the database in Todo operations through the 'Database.cs' context, instead of the previous in-memory solution, has been implemented.

### CODE REVIEW

**Comment by khalidabuhakmeh** [comment]
I'd also like to say to @kjeske that this is a pretty cool project and keep at it. I wish you the best of luck. Feel free to reach out to your JetBrains friends if you need help. :) 

Cheers 🍻

**Comment by ozkanpakdil** [comment]
@khalidabuhakmeh I am getting the error below

image

I just checkout the branch and then `dotnet run` below for future reference
image

**Comment by khalidabuhakmeh** [comment]
Be sure to run `dotnet ef database update` before running the app to create the database and table.

**Comment by kjeske** [comment]
Thank you @khalidabuhakmeh for this nice feature. Thank you also for kind words, I appreciate that!

**Pull request merged**
